#!/bin/bash

ver="$1"

cd data
rm -rf misaka.schema-$ver.zip
rm -rf misaka.schema-build-$ver.zip
zip -5 misaka.schema-$ver.zip *.yaml opencc/*
zip -5 misaka.schema-build-$ver.zip *.yaml opencc/* build/*

